name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.2"

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Check formatting
        run: deno fmt --check *.ts

      - name: Unit tests
        run: scripts/test

      - name: Test node imports
        run: |
          cd npm &&\
          npm install &&\
          cd .. &&\
          scripts/buildNode &&\
          scripts/testImports
